/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Cpu.c
**     Project     : M327
**     Processor   : MC56F84789VLL
**     Component   : MC56F84789VLL
**     Version     : Component 01.067, Driver 01.01, CPU db: 3.50.001
**     Datasheet   : MC56F847XXRM Rev.1 06/2012
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2016-10-12, 11:14, # CodeGen: 154
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.01
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */
#include "AS1.h"
#include "SM1.h"
#include "CSInput.h"
#include "Out0.h"
#include "Out1.h"
#include "Out2.h"
#include "Out3.h"
#include "Out4.h"
#include "Out5.h"
#include "Out6.h"
#include "Out7.h"
#include "Out8.h"
#include "Out9.h"
#include "Out10.h"
#include "Out11.h"
#include "Out12.h"
#include "Out13.h"
#include "Out14.h"
#include "Out15.h"
#include "Inp16.h"
#include "Inp1.h"
#include "TI1.h"
#include "MCBLDC.h"
#include "Enc1.h"
#include "Enc2.h"
#include "IFsh1.h"
#include "TMRA0.h"
#include "TMRA1.h"
#include "TMRA2.h"
#include "PWMC1.h"
#include "PWMA.h"
#include "SDA.h"
#include "SCL.h"
#include "CSPot.h"
#include "CSFlash.h"
#include "CAN1.h"
#include "AD1.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"


/* Global variables */
volatile word SR_lock = 0U;            /* Lock */
volatile word SR_reg;                  /* Current value of the SR register */

/*Definition of global shadow variables*/
word Shadow_GPIOB_DR;
word Shadow_GPIOC_DR;

/*
** ===================================================================
**     Method      :  Cpu_Interrupt (component MC56F84789VLL)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma interrupt alignsp
void Cpu_Interrupt(void)
{
/* This code can be changed using the CPU bean property "Build Options / Unhandled int code" */
  asm(DEBUGHLT);                       /* Halt the core and placing it in the debug processing state. */
  /* Here should be two NOPs if DEBUGHLT is removed.
  asm(nop);
  asm(nop); */
}

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC56F84789VLL)
**     Description :
**         Disables all maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC56F84789VLL)
**     Description :
**         Enables all maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC56F84789VLL)
**     Description :
**         Sets low power mode - Stop mode.
**         For more information about the stop mode see this CPU
**         documentation.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC56F84789VLL)
**     Description :
**         Sets low power mode - Wait mode.
**         For more information about the wait mode see this CPU
**         documentation.
**         Release from wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC56F84789VLL)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void init_56800_(void);         /* Forward declaration of external startup function declared in startup file */

/*** !!! Here you can place your own code using property "User data declarations" on the build options tab. !!! ***/

void _EntryPoint(void)
{
  #pragma constarray off

  /*** !!! Here you can place your own code before PE initialization using property "User code before PE initialization" on the build options tab. !!! ***/

  /*** ### MC56F84789VLL "Cpu" init code ... ***/

  /*** PE initialization code after reset ***/

  /* Disable watchdog after reset based on the setting of the "Watchdog" property in CPU component */
  /* COP_CTRL: ??=0,??=0,??=0,??=0,??=0,??=0,PSS=3,INTEN=0,CLKSEL=0,CLOREN=0,CSEN=0,CWEN=0,CEN=0,CWP=0 */
  setReg16(COP_CTRL, 0x0300U);          

  /* System clock initialization */
  setRegBitGroup(OCCS_OSCTL1, FREQ_TRIM8M, ((*(word *)0xE42C) & 0x03FFU)); /* Trim the 8MHz internal relaxation oscillator, frequency trim value */
  clrSetReg16Bits(OCCS_OSCTL1, OCCS_OSCTL1_ROPD_MASK, OCCS_OSCTL1_CLK_MODE_MASK); /* Enable internal 8MHz oscillator and select an external clock bypass mode */
  setRegBitGroup(OCCS_CTRL, PRECS, 0U); /* Select an internal 8MHz clock source for the CPU core */
  clrSetReg16Bits(OCCS_CTRL, OCCS_CTRL_PLLPD_MASK, OCCS_CTRL_LCKON_MASK); /* Enable PLL, LCKON and select clock source from prescaler */
  /* OCCS_DIVBY: LORTP=2,COD=0,??=0,??=0,PLLDB=0x31 */
  setReg16(OCCS_DIVBY, 0x2031U);       /* Set the clock prescalers */ 
  while(!getRegBit(OCCS_STAT, LCK0)){} /* Wait for PLL lock */
  setReg16Bits(OCCS_CTRL, OCCS_CTRL_ZSRC_MASK); /* Enable PLL, LCKON and select clock source from prescaler */
  /* OCCS_PROT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FRQEP=0,OSCEP=0,PLLEP=0 */
  setReg16(OCCS_PROT, 0x00U);          /* Set the OCCS protection register */ 
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code after PE initialization using property "User code after PE initialization" on the build options tab. !!! ***/

  asm(JMP init_56800_);                /* Jump to C startup code */
}

/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC56F84789VLL)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
      /* Initialization of the SIM module */
  /* SIM_MISC0: PIT_MSTR=0 */
  clrReg16Bits(SIM_MISC0, 0x01U);       
  /* SIM_CTRL: RST_FILT=0,DMAEbl=3,OnceEbl=0,STOP_disable=0,WAIT_disable=0 */
  clrSetReg16Bits(SIM_CTRL, 0x052FU, 0xC0U); 
  /* SIM_PWR: SR12STDBY=0,SR27PDN=0,SR27STDBY=0,LRSTDBY=0 */
  clrReg16Bits(SIM_PWR, 0xFFU);         
  /* SIM_CLKOUT: CLKODIV=0,CLKDIS1=1,CLKOSEL1=0,CLKDIS0=1,CLKOSEL0=0 */
  clrSetReg16Bits(SIM_CLKOUT, 0xE387U, 0x1020U); 
  /* SIM_PCE0: TA0=1,TA1=1,TA2=1,TA3=1,TB0=1,TB1=1,TB2=0,TB3=0,GPIOA=1,GPIOB=1,GPIOC=1,GPIOD=1,GPIOE=1,GPIOF=1,GPIOG=1 */
  clrSetReg16Bits(SIM_PCE0, 0x0300U, 0xFC7FU); 
  /* SIM_PCE1: DAC=0,SCI0=0,SCI1=0,SCI2=1,QSPI0=1,QSPI1=0,QSPI2=0,IIC0=0,IIC1=0,FLEXCAN=1 */
  clrSetReg16Bits(SIM_PCE1, 0x39E0U, 0x0601U); 
  /* SIM_PCE2: CMPA=0,CMPB=0,CMPC=0,CMPD=0,SARADC=0,CYCADC=1,CRC=0,QDC=0,PIT0=1,PIT1=0,PDB0=0,PDB1=0 */
  clrSetReg16Bits(SIM_PCE2, 0x1F37U, 0x88U); 
  /* SIM_PCE3: PWMACH0=1,PWMACH1=1,PWMACH2=1,PWMACH3=0,PWMBCH0=0,PWMBCH1=0,PWMBCH2=0,PWMBCH3=0 */
  clrSetReg16Bits(SIM_PCE3, 0x1FU, 0xE0U); 
  /* SIM_SD0: TA0=0,TA1=0,TA2=0,TA3=0,TB0=0,TB1=0,TB2=0,TB3=0,GPIOA=0,GPIOB=0,GPIOC=0,GPIOD=0,GPIOE=0,GPIOF=0,GPIOG=0 */
  clrReg16Bits(SIM_SD0, 0xFF7FU);       
  /* SIM_SD1: DAC=0,SCI0=0,SCI1=0,SCI2=0,QSPI0=0,QSPI1=0,QSPI2=0,IIC0=0,IIC1=0,FLEXCAN=0 */
  clrReg16Bits(SIM_SD1, 0x3FE1U);       
  /* SIM_SD2: CMPA=0,CMPB=0,CMPC=0,CMPD=0,SARADC=0,CYCADC=0,CRC=0,QDC=0,PIT0=0,PIT1=0,PDB0=0,PDB1=0 */
  clrReg16Bits(SIM_SD2, 0x1FBFU);       
  /* SIM_SD3: PWMACH0=0,PWMACH1=0,PWMACH2=0,PWMACH3=0,PWMBCH0=0,PWMBCH1=0,PWMBCH2=0,PWMBCH3=0 */
  clrReg16Bits(SIM_SD3, 0xFFU);         
  /* SIM_PROT: PMODE=0,GDP=0,PCEP=0,GIPSP=0 */
  clrReg16Bits(SIM_PROT, 0xFFU);        
  /* SIM_PCR: ??=0,??=0,SCI0_CR=1,SCI1_CR=1,SCI2_CR=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(SIM_PCR, 0x3800U);          /* Set the QSCI0; QSCI1; QSCI2 module clock rates */ 
      /* Initialization of the MCM module */
  /* MCM_UPRAMBAR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,RBA=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg32(MCM_UPRAMBAR, 0x00UL);       
  /* MCM_UFLASHBAR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FBA=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg32(MCM_UFLASHBAR, 0x00UL);      
  /* MCM_CPCR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,IBDIS=0,SRDIS=0,RCDIS=0,INSDIS=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg32(MCM_CPCR, 0x00UL);           
  /* MCM_RPCR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,RL=0,RPE=0 */
  setReg32(MCM_RPCR, 0x00UL);           
        /* Initialization of the PMC module */
  /* PMC_STS: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SR27=1,LVI=1,SLV27F=1,SLV22F=1,LV27F=0,LV22F=0 */
  setReg16(PMC_STS, 0x3CU);             
  /* PMC_CTRL: TRIM=*58413 */
  setReg16(PMC_CTRL, PMC_CTRL_TRIM_MASK & (*(word *)0xE42D));
      /* Initialization of the GPIOA module */
  /* GPIOA_DRIVE: DRIVE11=0,DRIVE10=0,DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOA_DRIVE, 0x0FFFU);   
  /* GPIOA_SRE: SRE11=1,SRE10=1,SRE9=1,SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOA_SRE, 0x0FFFU);     
      /* Initialization of the GPIOB module */
  /* GPIOB_DRIVE: DRIVE11=0,DRIVE10=0,DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOB_DRIVE, 0x0FFFU);   
  /* GPIOB_SRE: SRE11=1,SRE10=1,SRE9=1,SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOB_SRE, 0x0FFFU);     
      /* Initialization of the GPIOC module */
  /* GPIOC_DRIVE: DRIVE15=0,DRIVE14=0,DRIVE13=0,DRIVE12=0,DRIVE11=0,DRIVE10=0,DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIOC_DRIVE, 0x00U);         
  /* GPIOC_SRE: SRE15=1,SRE14=1,SRE13=1,SRE12=1,SRE11=1,SRE10=1,SRE9=1,SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16(GPIOC_SRE, 0xFFFFU);         
      /* Initialization of the GPIOD module */
  /* GPIOD_DRIVE: DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOD_DRIVE, 0xFFU);     
  /* GPIOD_SRE: SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=0,SRE2=1,SRE1=0,SRE0=1 */
  clrSetReg16Bits(GPIOD_SRE, 0x0AU, 0xF5U); 
      /* Initialization of the GPIOE module */
  /* GPIOE_DRIVE: DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOE_DRIVE, 0x03FFU);   
  /* GPIOE_SRE: SRE9=1,SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOE_SRE, 0x03FFU);     
      /* Initialization of the GPIOF module */
  /* GPIOF_DRIVE: DRIVE15=0,DRIVE14=0,DRIVE13=0,DRIVE12=0,DRIVE11=0,DRIVE10=0,DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIOF_DRIVE, 0x00U);         
  /* GPIOF_SRE: SRE15=1,SRE14=1,SRE13=1,SRE12=1,SRE11=1,SRE10=1,SRE9=1,SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16(GPIOF_SRE, 0xFFFFU);         
      /* Initialization of the GPIOG module */
  /* GPIOG_DRIVE: DRIVE11=0,DRIVE10=0,DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  clrReg16Bits(GPIOG_DRIVE, 0x0FFFU);   
  /* GPIOG_SRE: SRE11=1,SRE10=1,SRE9=1,SRE8=1,SRE7=1,SRE6=1,SRE5=1,SRE4=1,SRE3=1,SRE2=1,SRE1=1,SRE0=1 */
  setReg16Bits(GPIOG_SRE, 0x0FFFU);     
/*lint -save  -e586 Disable MISRA rule (2.1) checking. Functionality is implemented using assembler. */
  /* Shadow registers initialization */
  asm {
    swap shadows
    nop
    nop
    move.l #0, R0
    move.l #0, R1
    move.l #0, R2
    move.l #0, R3
    move.l #0, R4
    move.l #0, R5
    move.l #0, N
    moveu.w #65535, N3
    moveu.w #65535, M01
    nop
    nop
    swap shadows
  }
/*lint -restore Enable MISRA rule (2.1) checking. */
  /* Common initialization of the CPU registers */
  /* GPIOD_PER: PE7=0,PE6=1,PE5=1,PE4=1 */
  clrSetReg16Bits(GPIOD_PER, 0x80U, 0x70U); 
  /* SIM_GPSDL: D6=0,D5=0 */
  clrReg16Bits(SIM_GPSDL, 0x3C00U);     
  /* INTC_IPR4: QSCI2_TDRE=2,QSCI2_TIDLE=2,QSCI2_RCV=2,QSCI2_RERR=2,CAN_RX_WARN=2 */
  clrSetReg16Bits(INTC_IPR4, 0x0551U, 0x0AA2U); 
  /* INTC_IPR6: QSPI0_RCV=3,QSPI0_XMIT=2 */
  clrSetReg16Bits(INTC_IPR6, 0x10U, 0xE0U); 
  /* GPIOC_PER: PE15=0,PE14=0,PE12=1,PE11=1,PE10=1,PE9=1,PE8=1,PE7=0,PE6=1,PE4=1,PE3=1,PE2=1,PE0=0 */
  clrSetReg16Bits(GPIOC_PER, 0xC081U, 0x1F5CU); 
  /* SIM_GPSCH: C12=0,C11=0,C10=0,C9=0,C8=0 */
  clrReg16Bits(SIM_GPSCH, 0x03F7U);     
  /* GPIOG_IENR: IEN11=0,IEN10=0,IEN9=0,IEN6=0 */
  clrReg16Bits(GPIOG_IENR, 0x0E40U);    
  /* GPIOG_IAR: IA11=0,IA10=0,IA9=0,IA6=0 */
  clrReg16Bits(GPIOG_IAR, 0x0E40U);     
  /* GPIOG_IESR: IES11=1,IES10=1,IES9=1,IES6=1 */
  setReg16Bits(GPIOG_IESR, 0x0E40U);    
  /* GPIOG_PPMODE: PPMODE11=1,PPMODE10=1,PPMODE9=1,PPMODE6=1 */
  setReg16Bits(GPIOG_PPMODE, 0x0E40U);  
  /* GPIOG_DR: D11=0,D10=1,D9=0,D6=0 */
  clrSetReg16Bits(GPIOG_DR, 0x0A40U, 0x0400U); 
  /* GPIOG_DDR: DD11=1,DD10=1,DD9=1,DD6=1 */
  setReg16Bits(GPIOG_DDR, 0x0E40U);     
  /* GPIOG_PER: PE11=0,PE10=0,PE9=0,PE6=0 */
  clrReg16Bits(GPIOG_PER, 0x0E40U);     
  /* GPIOB_IENR: IEN11=0,IEN10=0,IEN9=0,IEN8=0,IEN6=0,IEN4=0,IEN3=0,IEN2=0,IEN1=0,IEN0=0 */
  clrReg16Bits(GPIOB_IENR, 0x0F5FU);    
  /* GPIOB_IAR: IA11=0,IA10=0,IA9=0,IA8=0,IA6=0,IA4=0,IA3=0,IA2=0,IA1=0,IA0=0 */
  clrReg16Bits(GPIOB_IAR, 0x0F5FU);     
  /* GPIOB_IESR: IES11=1,IES10=1,IES9=1,IES8=1,IES6=1,IES4=1,IES3=1,IES2=1,IES1=1,IES0=1 */
  setReg16Bits(GPIOB_IESR, 0x0F5FU);    
  /* GPIOB_PPMODE: PPMODE11=1,PPMODE10=1,PPMODE9=1,PPMODE8=1,PPMODE6=1,PPMODE4=1,PPMODE3=1,PPMODE2=1,PPMODE1=1,PPMODE0=1 */
  setReg16Bits(GPIOB_PPMODE, 0x0F5FU);  
  /* GPIOB_DR: D11=0,D10=0,D9=0,D8=0,D6=0,D4=0,D3=0,D2=0,D1=0,D0=0 */
  clrReg16Bits(GPIOB_DR, 0x0F5FU);      
  /* GPIOB_DDR: DD11=1,DD10=1,DD9=1,DD8=1,DD6=1,DD4=1,DD3=1,DD2=1,DD1=1,DD0=1 */
  setReg16Bits(GPIOB_DDR, 0x0F5FU);     
  /* GPIOB_PER: PE11=0,PE10=0,PE9=0,PE8=0,PE6=0,PE4=0,PE3=0,PE2=0,PE1=0,PE0=0 */
  clrReg16Bits(GPIOB_PER, 0x0F5FU);     
  /* GPIOB_PUR: PU8=0,PU2=0 */
  clrReg16Bits(GPIOB_PUR, 0x0104U);     
  /* GPIOA_IENR: IEN11=0 */
  clrReg16Bits(GPIOA_IENR, 0x0800U);    
  /* GPIOA_IAR: IA11=0 */
  clrReg16Bits(GPIOA_IAR, 0x0800U);     
  /* GPIOA_IESR: IES11=1 */
  setReg16Bits(GPIOA_IESR, 0x0800U);    
  /* GPIOA_PPMODE: PPMODE11=1 */
  setReg16Bits(GPIOA_PPMODE, 0x0800U);  
  /* GPIOA_DR: D11=0 */
  clrReg16Bits(GPIOA_DR, 0x0800U);      
  /* GPIOA_DDR: DD11=1 */
  setReg16Bits(GPIOA_DDR, 0x0800U);     
  /* GPIOA_PER: PE11=0,PE0=1 */
  clrSetReg16Bits(GPIOA_PER, 0x0800U, 0x01U); 
  /* GPIOC_IENR: IEN15=0,IEN14=0,IEN7=0,IEN0=0 */
  clrReg16Bits(GPIOC_IENR, 0xC081U);    
  /* GPIOC_IAR: IA15=0,IA14=0,IA7=0,IA0=0 */
  clrReg16Bits(GPIOC_IAR, 0xC081U);     
  /* GPIOC_IESR: IES15=1,IES14=1,IES7=1,IES0=1 */
  setReg16Bits(GPIOC_IESR, 0xC081U);    
  /* GPIOC_PPMODE: PPMODE15=1,PPMODE14=1,PPMODE7=1,PPMODE0=1 */
  setReg16Bits(GPIOC_PPMODE, 0xC081U);  
  /* GPIOC_DR: D15=0,D14=0,D7=0,D0=0 */
  clrReg16Bits(GPIOC_DR, 0xC081U);      
  /* GPIOC_DDR: DD15=1,DD14=1,DD7=1,DD0=1 */
  setReg16Bits(GPIOC_DDR, 0xC081U);     
  /* GPIOD_IENR: IEN7=0 */
  clrReg16Bits(GPIOD_IENR, 0x80U);      
  /* GPIOD_IAR: IA7=0 */
  clrReg16Bits(GPIOD_IAR, 0x80U);       
  /* GPIOD_IESR: IES7=1 */
  setReg16Bits(GPIOD_IESR, 0x80U);      
  /* GPIOD_PPMODE: PPMODE7=1 */
  setReg16Bits(GPIOD_PPMODE, 0x80U);    
  /* GPIOD_DR: D7=0 */
  clrReg16Bits(GPIOD_DR, 0x80U);        
  /* GPIOD_DDR: DD7=1 */
  setReg16Bits(GPIOD_DDR, 0x80U);       
  /* GPIOF_IENR: IEN15=0,IEN14=0,IEN11=0 */
  clrReg16Bits(GPIOF_IENR, 0xC800U);    
  /* GPIOF_IAR: IA15=0,IA14=0,IA11=0 */
  clrReg16Bits(GPIOF_IAR, 0xC800U);     
  /* GPIOF_IESR: IES15=1,IES14=1,IES11=1 */
  setReg16Bits(GPIOF_IESR, 0xC800U);    
  /* GPIOF_PPMODE: PPMODE15=1,PPMODE11=1 */
  setReg16Bits(GPIOF_PPMODE, 0x8800U);  
  /* GPIOF_DR: D15=0,D11=0 */
  clrReg16Bits(GPIOF_DR, 0x8800U);      
  /* GPIOF_DDR: DD15=1,DD14=0,DD11=1 */
  clrSetReg16Bits(GPIOF_DDR, 0x4000U, 0x8800U); 
  /* GPIOF_PER: PE15=0,PE14=0,PE11=0,PE8=1,PE7=1,PE6=1 */
  clrSetReg16Bits(GPIOF_PER, 0xC800U, 0x01C0U); 
  /* GPIOF_PUR: PU14=0,PU8=0,PU7=0,PU6=0 */
  clrReg16Bits(GPIOF_PUR, 0x41C0U);     
  /* GPIOC_PUR: PU14=0,PU2=0,PU0=0 */
  clrReg16Bits(GPIOC_PUR, 0x4005U);     
  /* INTC_IPR10: PIT0_ROLLOVR=2,FTFL_CC=2 */
  clrSetReg16Bits(INTC_IPR10, 0x1001U, 0x2002U); 
  /* SIM_GPSCL: C6=0,C4=0,C3=0,C2=1 */
  clrSetReg16Bits(SIM_GPSCL, 0x33E0U, 0x10U); 
  /* SIM_IPS0: TB3=0,TB2=0,TB1=0,TB0=0,TA2=0,TA1=0,TA0=0,PWMAF0=0 */
  clrReg16Bits(SIM_IPS0, 0xF701U);      
  /* SIM_GPSFH: F8=1 */
  clrSetReg16Bits(SIM_GPSFH, 0x02U, 0x01U); 
  /* TMRB_0_ENBL: ENBL&=~3 */
  clrReg16Bits(TMRB_0_ENBL, 0x03U);     
  /* SIM_GPSFL: F7=0,F6=0 */
  clrReg16Bits(SIM_GPSFL, 0xF000U);     
  /* INTC_IPR2: ADC_ERR=2,ADC_CC0=2,TMRA_0=3,TMRA_1=3,TMRA_2=3 */
  clrSetReg16Bits(INTC_IPR2, 0x1400U, 0x28FCU); 
  /* GPIOE_PER: PE8=1,PE5=1,PE4=1,PE3=1,PE2=1,PE1=1,PE0=1 */
  setReg16Bits(GPIOE_PER, 0x013FU);     
  /* SIM_GPSEL: E5=0,E4=0 */
  clrReg16Bits(SIM_GPSEL, 0x0500U);     
  /* SIM_GPSEH: E8=1 */
  setReg16Bits(SIM_GPSEH, 0x01U);       
  /* INTC_IPR8: PWMA_FAULT=0 */
  clrReg16Bits(INTC_IPR8, 0x0300U);     
  /* INTC_IPR3: CAN_TX_WARN=2,CAN_ERROR=2,CAN_BUS_OFF=2,CAN_MB_OR=2 */
  clrSetReg16Bits(INTC_IPR3, 0x5500U, 0xAA00U); 
  /* SIM_GPSAL: A0=0 */
  clrReg16Bits(SIM_GPSAL, 0x01U);       
  /* Initialization of the SIM module */
  /* SIM_PCE0: GPIOE=0 */
  clrReg16Bits(SIM_PCE0, 0x04U);        
  /* ### Asynchro serial "AS1" init code ... */
  AS1_Init();
  /* ### SynchroMaster "SM1" init code ... */
  SM1_Init();
  /* ### BitIO "Out3" init code ... */
  Shadow_GPIOB_DR &= ~(word)0x0100U;   /* Initialize shadow variable */
  /* ### BitIO "Out5" init code ... */
  Shadow_GPIOB_DR &= ~(word)0x04U;     /* Initialize shadow variable */
  /* ### BitIO "Inp1" init code ... */
  Shadow_GPIOC_DR &= ~(word)0x01U;     /* Initialize shadow variable */
  /* ### TimerInt "TI1" init code ... */
  TI1_Init();
  /* ### PulseAccumulator "Enc1" init code ... */
  Enc1_Init();
  /* ### PulseAccumulator "Enc2" init code ... */
  Enc2_Init();
  IFsh1_Init();
  /* ### Init_TMR "TMRA0" init code ... */
  TMRA0_Init();
  /* ### Init_TMR "TMRA1" init code ... */
  TMRA1_Init();
  /* ### Init_TMR "TMRA2" init code ... */
  TMRA2_Init();
  /* ### Init_eFlexPWM "PWMA" init code ... */
  /* ### Call "PWMA_Init();" init method in a user code, i.e. in the main code */

  /* ### Note:   To enable automatic calling of the "PWMA" init code here,
                 the 'Call Init method' property must be set to 'yes'.
   */
  /* ### PWMMC "PWMC1" init code ... */
  PWMC1_Init();


  /* ### BitIO "SDA" init code ... */
  Shadow_GPIOC_DR &= ~(word)0x4000U;   /* Initialize shadow variable */
  /* ###  "CAN1" init code ... */
  CAN1_Init();
  /* ### ADC "AD1" init code ... */
  AD1_Init();
  /* Common peripheral initialization - ENABLE */
  /* TMRB_0_ENBL: ENBL|=3 */
  setReg16Bits(TMRB_0_ENBL, 0x03U);     
  /* TMRA_0_ENBL: ENBL|=7 */
  setReg16Bits(TMRA_0_ENBL, 0x07U);     
  __EI(0);                             /* Enable interrupts of the selected priority level */
}

/* END Cpu. */

